#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ${BASEDIR};
# Install Vim
# ===========
rm  ~/.vim/bundle/Vundle.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
rm -rf ~/.vimrc
rm -rf ~/.gvimrc
ln -s ${BASEDIR}/vim/vimrc ~/.vimrc
ln -s ${BASEDIR}/vim/gvimrc ~/.gvimrc
vim +PluginInstall +qall

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install ack
brew install macvim

echo "*/10 * * * *  ${BASEDIR}/run_c_tags.sh" >> mycron
crontab mycron
rm mycron

./run_c_tags.sh
